version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB:       elibrary
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password123@db:5432/elibrary
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./book_files:/app/book_files

volumes:
  postgres_data: