version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: elibrary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abhisek123  # You can keep this or change it to 'abhisek123'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: